# Generated by Django 4.2.1 on 2023-07-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hamburguesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('historia', models.TextField(blank=True)),
                ('calorias', models.DecimalField(decimal_places=2, max_digits=8)),
                ('proteinas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carbohidratos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grasas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sodio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
