# Generated by Django 4.2.1 on 2023-07-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbMenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='hamburguesas/'),
        ),
    ]
