# Generated by Django 4.2.1 on 2023-07-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbMenu', '0002_hamburguesa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img-bgr/'),
        ),
    ]
