# Generated by Django 4.2.1 on 2023-07-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbMenu', '0003_alter_hamburguesa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='hamburguesas/'),
        ),
    ]
