# Generated by Django 4.2.2 on 2023-07-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbMenu', '0004_alter_hamburguesa_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesa',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
