# Generated by Django 4.2.1 on 2023-07-10 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbMenu', '0006_compra_carritoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
