# Generated by Django 4.2.1 on 2023-06-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('ciudadId', models.AutoField(db_column=' ciudadId', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tipoMensaje',
            fields=[
                ('mensajeId', models.AutoField(db_column=' mensajeId', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=30)),
                ('comentario', models.CharField(max_length=400)),
                ('ciudadId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.ciudad')),
                ('mensajeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.tipomensaje')),
            ],
        ),
    ]
