# Generated by Django 4.2.1 on 2023-06-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=30)),
                ('tipoMensaje', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=400)),
            ],
        ),
    ]
