# Generated by Django 4.2.1 on 2023-06-21 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoMensaje',
            fields=[
                ('mensajeId', models.AutoField(db_column=' mensajeId', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='tipoMensaje',
        ),
        migrations.AddField(
            model_name='feedback',
            name='mensajeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Soporte.tipomensaje'),
            preserve_default=False,
        ),
    ]
