# Generated by Django 4.2.2 on 2023-07-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_alter_feedback_ciudadid_alter_feedback_mensajeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ciudadId',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='mensajeId',
        ),
        migrations.AddField(
            model_name='feedback',
            name='tipo_fb',
            field=models.IntegerField(choices=[[0, 'Felicitación'], [1, 'Sugerencia'], [2, 'Reclamo']], default=1),
            preserve_default=False,
        ),
    ]
