# Generated by Django 4.2.2 on 2023-07-08 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0003_remove_feedback_ciudadid_remove_feedback_mensajeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ciudadId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.ciudad'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='mensajeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.tipomensaje'),
        ),
    ]
