# Generated by Django 4.2.2 on 2023-07-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0004_feedback_ciudadid_feedback_mensajeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='tipo_fb',
        ),
    ]
